[package]
name = "leptless"
version = "0.1.0"
edition = "2021"

[dependencies]
pdfium-render = "0.8"
image = "0.25"

# Leptess with layout-aware API (get_words, set_variable, etc.)
leptess = { git = "https://github.com/houqp/leptess.git", branch = "master" }
anyhow = "1.0.99"
